# Site settings
title:       "% Project"
header_title: "Percentage Project"
webmaster:      "Alexander Goodkind <alexander@goodkind.io>"
author: "The University of Pennsylvania Women in Computer Science (Penn WiCS) "
description: "The #PercentageProject19 is an artistic, visual outlet for data collected from an anonymous survey of University of Pennsylvania Computer Science students in early 2019. The Percentage Project was founded in 2018 with the goal of showcasing data along with advocates to put a face to the statistic. We aim to encourage reflection and conversation on the experiences of minority students beyond just how many minority students we have."

baseurl:    "" # no trailing slash !
url:         "https://percentageproject.com"
date_format: "%-d.%m.%Y"

defaults:
  - scope:
      path: "photos/photos_compressed"
    values:
      image: true

# include trailing slash !!!
favicon_path: "/assets/img/favicons/"  
css_path: "/assets/css/"
js_path: "/assets/js/"

# Google Analytics
google_analytics_tracking_code: UA-137802583-1

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
